runtime: nodejs18
service: frontend

env_variables:
  NEXT_PUBLIC_API_URL: "https://backend-dot-curious-kingdom-465619-v1.uc.r.appspot.com"

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10 