services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: scholar_analyzer_db
    environment:
      POSTGRES_DB: scholar_analyzer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - scholar_network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: scholar_analyzer_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scholar_network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: scholar_analyzer_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/scholar_analyzer
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - scholar_network
    restart: unless-stopped

  # Next.js Frontend  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: scholar_analyzer_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - scholar_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  scholar_network:
    driver: bridge