runtime: python39
service: backend

env_variables:
  DATABASE_URL: "postgresql://postgres:password@/postgres?host=/cloudsql/curious-kingdom-465619-v1:us-central1:scholar-db"
  REDIS_URL: "redis://redis-memorystore:6379"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: curious-kingdom-465619-v1:us-central1:scholar-db 